# Generated by Django 5.1.5 on 2025-04-17 15:17

import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='کد یکبارمصرف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ایجاد شده در')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='ارسال پیامک در')),
                ('limited_at', models.DateTimeField(blank=True, null=True, verbose_name='محدود شده در')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[user.validators.phone_validator], verbose_name='تلفن همراه')),
                ('retries_count', models.IntegerField(default=0, verbose_name='تعداد تلاش برای وریفای ناموفق')),
                ('ip_address', models.CharField(blank=True, null=True, verbose_name='آدرس IP')),
            ],
            options={
                'verbose_name': 'کد یکبارمصرف',
                'verbose_name_plural': 'کدهای یکبارمصرف',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='نام')),
                ('family', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=11, validators=[user.validators.phone_validator], verbose_name='تلفن همراه')),
                ('email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='ایمیل')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='پسورد')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروز شده در')),
                ('limited_at', models.DateTimeField(blank=True, null=True, verbose_name='محدود شده در')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تعلیق')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, validators=[user.validators.phone_validator], verbose_name='تلفن همراه')),
                ('ip_address', models.CharField(verbose_name='آدرس IP')),
                ('retries_count', models.IntegerField(default=0, verbose_name='تعداد تلاش مجدد')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ایجاد شده در')),
            ],
        ),
    ]
